cutoff_len: 1024
dataset: identity
dataset_dir: /root/autodl-fs/finetune_data
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: auto
fp16: true
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: meta-llama/Meta-Llama-3-8B
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/LLaMA3-8B/lora/train_2024-06-26-23-41-28
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
warmup_steps: 0
